server:
  jetty:
    threads:
      max: 50
  port: ${PORT:8080}

dialogflow:

spring:
  data:
    mongodb:
      uri: url
channels:
  telegram:
    token: change it
    webhook: webhook_url

sentry:
  dsn:

